baseURL = "https://parallel-ssh.org/"
languageCode = "en-us"
title = "ParallelSSH"
theme = "beautifulhugo"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "parallel-ssh"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-9132694-6"
paginate = 5
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
enableRobotsTXT = true

[Params]
  logo = "/static/avatar-icon.png"
  favicon = "/static/favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false

[Author]
  name = "Panos Kittenis"
  website = "parallel-ssh.org"
  email = "zuboci@yandex.com"
  github = "ParallelSSH"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 3

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 2

[[menu.main]]
    parent = "projects"
    name = "parallel-ssh"
    url = "https://github.com/ParallelSSH/parallel-ssh"
    weight = 1

[[menu.main]]
    parent = "projects"
    name = "ssh2-python"
    url = "https://github.com/ParallelSSH/ssh2-python"
    weight = 2
